"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AssessmentTag, SafeText } from "./data-ui";
import { formatDate } from "../_lib/format";
import type { DecisionReview as Review } from "../_lib/types";

const API_BASE = (process.env.NEXT_PUBLIC_RIELVEST_API_URL ?? "http://localhost:4000/api").replace(/\/$/, "");

/** Fetch only when requested; no model calls or extra dashboard cards. */
export function DecisionReview({ symbol }: { symbol: string }) {
  const [open, setOpen] = useState(false);
  return (
    <details className="decision-review" onToggle={(event) => setOpen(event.currentTarget.open)}>
      <summary>Before you consider buying</summary>
      {open ? <ReviewContent key={symbol} symbol={symbol} /> : null}
    </details>
  );
}

function ReviewContent({ symbol }: { symbol: string }) {
  const [review, setReview] = useState<Review | null>(null);
  const [error, setError] = useState(false);
  const [attempt, setAttempt] = useState(0);

  useEffect(() => {
    const controller = new AbortController();
    const timer = window.setTimeout(() => controller.abort(), 12_000);
    let active = true;
    fetch(`${API_BASE}/companies/${encodeURIComponent(symbol)}/decision-review`, { signal: controller.signal })
      .then(async (response) => {
        if (!response.ok) throw new Error("Review unavailable");
        const body = await response.json() as { review: Review };
        if (!body.review || body.review.symbol !== symbol) throw new Error("Invalid review");
        if (active) setReview(body.review);
      })
      .catch(() => { if (active) setError(true); })
      .finally(() => window.clearTimeout(timer));
    return () => { active = false; window.clearTimeout(timer); controller.abort(); };
  }, [symbol, attempt]);

  if (error) return (
    <div role="alert" className="review-body">
      <p>The decision review is temporarily unavailable.</p>
      <button type="button" className="text-button" onClick={() => { setError(false); setAttempt((value) => value + 1); }}>Try again</button>
    </div>
  );
  if (!review) return <p role="status" className="review-body">Checking company figures and trading conditions…</p>;

  return (
    <div className="review-body">
      <div className="review-heading">
        <strong>{review.headline}</strong>
        <span>{formatDate(review.asOf)} · {review.factors.filter((factor) => factor.score !== null).length}/{review.factors.length} categories scored</span>
      </div>
      <div className="review-balance">
        <div>
          <h4>What supports it</h4>
          {review.strengths.length ? review.strengths.map((line) => <p key={line}><SafeText>{line}</SafeText></p>) : <p>No clear positive finding in the available data.</p>}
        </div>
        <div>
          <h4>Reasons to wait</h4>
          {review.cautions.length ? review.cautions.map((line) => <p key={line}><SafeText>{line}</SafeText></p>) : <p>No major caution was detected. Missing data can still hide risks.</p>}
        </div>
      </div>
      <p className="review-next"><strong>Next check:</strong> <SafeText>{review.nextCheck}</SafeText></p>
      <details className="review-evidence">
        <summary>Factors, filings and explanation</summary>
        <dl className="review-factors">
          {review.factors.map((factor) => <div key={factor.label}><dt>{factor.label}</dt><dd><AssessmentTag value={factor.assessment} /></dd></div>)}
        </dl>
        {review.summary.lines.length > 0 ? <>
          <h4>{review.summary.source === "model" ? "Gemini explanation" : "Data-based explanation"}</h4>
          <p className="review-meta">{review.summary.source === "model" ? `AI-generated from recorded data · ${review.summary.model ?? "Gemini"}. Verify against the factors and filings.` : "Generated by RielVest’s analysis rules."}</p>
          {review.summary.lines.map((line, index) => <p key={index}><SafeText>{line}</SafeText></p>)}
        </> : null}
        {review.news.length ? <><h4>Latest filings</h4>{review.news.map((item) => <p key={`${item.date}-${item.title}`}>
          <span>{formatDate(item.date)} · </span>
          {item.url ? <a href={item.url} target="_blank" rel="noreferrer noopener"><SafeText>{item.title}</SafeText></a> : <SafeText>{item.title}</SafeText>}
        </p>)}</> : null}
        {review.gaps.length ? <><h4>Still unknown</h4>{review.gaps.map((gap) => <p key={gap}><SafeText>{gap}</SafeText></p>)}</> : null}
        <p>Coverage counts scored categories; it is not the chance of making a profit. This review does not account for your holdings, time horizon or risk tolerance.</p>
        <Link href={`/stocks/${symbol}`}>Open full company analysis</Link>
      </details>
    </div>
  );
}
